export const mockSettlements = [
  {
    id: 1,
    groupId: 1,
    groupName: 'Roommates',
    from: 'Bob Smith',
    to: 'Alice Johnson',
    description: 'Rent share - December',
    amount: 300,
    status: 'pending',
    date: '2024-12-15',
  },
  {
    id: 2,
    groupId: 1,
    groupName: 'Roommates',
    from: 'Carol Williams',
    to: 'Alice Johnson',
    description: 'Utilities - December',
    amount: 175,
    status: 'pending',
    date: '2024-12-10',
  },
  {
    id: 3,
    groupId: 1,
    groupName: 'Roommates',
    from: 'Carol Williams',
    to: 'Bob Smith',
    description: 'Groceries split',
    amount: 95,
    status: 'pending',
    date: '2024-12-08',
  },
  {
    id: 4,
    groupId: 2,
    groupName: 'Trip to Goa',
    from: 'David Lee',
    to: 'Alice Johnson',
    description: 'Hotel booking share',
    amount: 120,
    status: 'settled',
    date: '2024-11-20',
  },
  {
    id: 5,
    groupId: 2,
    groupName: 'Trip to Goa',
    from: 'David Lee',
    to: 'Bob Smith',
    description: 'Fuel expenses',
    amount: 55,
    status: 'settled',
    date: '2024-11-18',
  },
  {
    id: 6,
    groupId: 2,
    groupName: 'Trip to Goa',
    from: 'Emma Davis',
    to: 'Carol Williams',
    description: 'Food & dining',
    amount: 210,
    status: 'pending',
    date: '2024-11-22',
  },
  {
    id: 7,
    groupId: 3,
    groupName: 'Office Lunch Club',
    from: 'Frank Miller',
    to: 'David Lee',
    description: 'Weekly lunch pool',
    amount: 45,
    status: 'settled',
    date: '2024-12-12',
  },
  {
    id: 8,
    groupId: 3,
    groupName: 'Office Lunch Club',
    from: 'Grace Wilson',
    to: 'Alice Johnson',
    description: 'Team outing contribution',
    amount: 85,
    status: 'pending',
    date: '2024-12-14',
  },
  {
    id: 9,
    groupId: 4,
    groupName: 'Family Utilities',
    from: 'Henry Taylor',
    to: 'Alice Johnson',
    description: 'Electricity bill - Nov',
    amount: 160,
    status: 'pending',
    date: '2024-12-01',
  },
  {
    id: 10,
    groupId: 4,
    groupName: 'Family Utilities',
    from: 'Ivy Brown',
    to: 'Bob Smith',
    description: 'Internet bill - Nov',
    amount: 75,
    status: 'settled',
    date: '2024-11-28',
  },
  {
    id: 11,
    groupId: 4,
    groupName: 'Family Utilities',
    from: 'Henry Taylor',
    to: 'Carol Williams',
    description: 'Water bill - Nov',
    amount: 40,
    status: 'pending',
    date: '2024-11-25',
  },
  {
    id: 12,
    groupId: 5,
    groupName: 'Weekend Getaway',
    from: 'Jack Anderson',
    to: 'David Lee',
    description: 'Cabin rental',
    amount: 350,
    status: 'pending',
    date: '2024-12-05',
  },
  {
    id: 13,
    groupId: 5,
    groupName: 'Weekend Getaway',
    from: 'Kate Thomas',
    to: 'Emma Davis',
    description: 'Food supplies',
    amount: 130,
    status: 'settled',
    date: '2024-12-03',
  },
  {
    id: 14,
    groupId: 1,
    groupName: 'Roommates',
    from: 'Alice Johnson',
    to: 'Carol Williams',
    description: 'Cleaning supplies',
    amount: 25,
    status: 'pending',
    date: '2024-12-18',
  },
  {
    id: 15,
    groupId: 3,
    groupName: 'Office Lunch Club',
    from: 'Bob Smith',
    to: 'Grace Wilson',
    description: 'Coffee run reimbursement',
    amount: 18,
    status: 'settled',
    date: '2024-12-16',
  },
]
